### Problem Statement 

### The objective is to predict whether a customer will give a high tip based on features like bill amount, time, and group size.

### This helps restaurants understand customer behavior and identify high-value customers using the CatBoost algorithm.

In [ ]:
from catboost import CatBoostClassifier # is this working ?

In [2]:
# why is required ?

# !pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp39-cp39-win_amd64.whl (100.2 MB)
     -------------------------------------- 100.2/100.2 MB 1.1 MB/s eta 0:00:00
Requirement already satisfied: six in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: scipy in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (1.9.1)
Requirement already satisfied: plotly in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (5.9.0)
Requirement already satisfied: graphviz in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (0.20.1)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (1.24.4)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (1.4.4)
Requirement already satisfied: matplotlib in c:\users\askpr\anaconda3\lib\site-packages (from catboost) (3.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\askpr\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\askpr\anaconda3\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\askpr\anaconda3\lib\site-packages (from matplotlib->catboost) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\askpr\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\askpr\anaconda3\lib\site-packages (from matplotlib->catboost) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\askpr\anaconda3\lib\site-packages (from matplotlib->catboost) (9.2.0)
Requirement already satisfied: packaging>=20.0 in c:\users\askpr\anaconda3\lib\site-packages (from matplotlib->catboost) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\askpr\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\askpr\anaconda3\lib\site-packages (from plotly->catboost) (8.2.3)
Installing collected packages: catboost
Successfully installed catboost-1.2.10

WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\askpr\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ensorflow-intel (c:\users\askpr\anaconda3\lib\site-packages)

In [1]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

In [2]:

# Load dataset
df = pd.read_csv("tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
df.tail()

     total_bill   tip     sex smoker   day    time  size  target
239       29.03  5.92    Male     No   Sat  Dinner     3       1
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       0
242       17.82  1.75    Male     No   Sat  Dinner     2       0
243       18.78  3.00  Female     No  Thur  Dinner     2       0

In [3]:
# Create target variable (classification)
# High tip if tip > 3
df['target'] = (df['tip'] > 3).astype(int)

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size  target
0       16.99  1.01  Female     No  Sun  Dinner     2       0
1       10.34  1.66    Male     No  Sun  Dinner     3       0
2       21.01  3.50    Male     No  Sun  Dinner     3       1
3       23.68  3.31    Male     No  Sun  Dinner     2       1
4       24.59  3.61  Female     No  Sun  Dinner     4       1

In [8]:
# Features and target
X = df.drop(['tip', 'target'], axis=1)   # remove tip (used to create target)
y = df['target']

In [9]:
X.head()

   total_bill     sex smoker  day    time  size
0       16.99  Female     No  Sun  Dinner     2
1       10.34    Male     No  Sun  Dinner     3
2       21.01    Male     No  Sun  Dinner     3
3       23.68    Male     No  Sun  Dinner     2
4       24.59  Female     No  Sun  Dinner     4

In [11]:
# Identify categorical columns
cat_cols = X.select_dtypes(include=['object']).columns.tolist()
cat_cols

['sex', 'smoker', 'day', 'time']

In [12]:


# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
X_train.shape,y_train.shape

((195, 6), (195,))

In [27]:
# Train CatBoost model
model = CatBoostClassifier(
    iterations=200,      # Number of trees (models) to build step by step
    learning_rate=0.1,   # How much each tree contributes (smaller = slower but better learning)
    depth=5,             # Depth of each tree (controls how complex each tree is)
    verbose=0            # Controls output during training (0 = no training logs printed)
)

In [28]:
model.fit(X_train, y_train, cat_features=cat_cols)

CatBoostClassifier(depth=5, iterations=200, learning_rate=0.1, verbose=0)

In [17]:


# Predict
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7551020408163265